config/routes.rb
Rails.application.routes.draw do
  get 'room/show'
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show]

  resources :foods do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end

  resources :users do
    member do
     get :following, :followers
    end
  end
  resources :relationships,       only: [:create, :destroy]

  resources :messages, :only => [:create]
  
  resources :rooms, :only => [:create, :show]
  
  root 'foods#index'
end

app/models/food.rb
class Food < ApplicationRecord
    belongs_to :user

    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user

    has_many :comments, dependent: :destroy

    mount_uploader :image, ImageUploader
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]  
  def index
        if params[:search] == nil
          @foods= Food.all
        elsif params[:search] == ''
          @foods=Food.all
        else
          #部分検索
          @foods = Food.where("name LIKE ? ",'%' + params[:search] + '%')
        end

        @foods = @foods.page(params[:page]).per(3)
    end

    def new
        @foods = Food.new
      end
    
      def create
        food = Food.new(food_params)
        food.user_id = current_user.id
        if food.save!
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
      end

      def show
        @food = Food.find(params[:id])
        @comments = @food.comments
        @comment = Comment.new
      end

      def edit
        @food = Food.find(params[:id])
      end

      def update
        food = Food.find(params[:id])
        if food.update(food_params)
          redirect_to :action => "show", :id => food.id
        else
          redirect_to :action => "new"
        end
      end  

      def destroy
        food = Food.find(params[:id])
        food.destroy
        redirect_to action: :index
      end

      private
      def food_params
        params.require(:food).permit(:name, :genre, :address, :cost, :about, :date, :overall, :image, :lat, :lng)
      end
end

app/helpers/foods_helper.rb
module FoodsHelper
    def getPercent(number) 
        if number.present?
          calPercent = number/5.to_f * 100
          percent = calPercent.round
          return percent.to_s
        else
          return 0
        end
    end
     
end

app/views/foods/edit.html.erb
<%= form_for @food do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, :size => 140 %> 
    <%= f.submit "編集する" %>
  <% end %>

app/views/foods/index.html.erb
<h1>中目黒の美味いごはん</h1>
<h3>一覧ページ</h3>
<%= link_to "新規投稿へ", new_food_path %>

<% if user_signed_in? %>
  <%= link_to "マイページへ", user_path(current_user.id) %>
<% end %>

<h3>投稿を検索</h3>
 <%= form_tag({controller:"foods",action:"index"}, method: :get) do %>
   <%= text_field_tag :search %>
   <%= submit_tag '検索する'  %>
<% end %>

<h3>投稿一覧</h3>



<%= page_entries_info @foods %>
<div class="foods-container">
  <% @foods.each do |t| %>
    <div class="food">
    <%= image_tag t.image_url, size: "250x200" if t.image? %>
    <%= link_to t.user.name, user_path(t.user.id) %>
      <%= t.user.email %>
      <%= t.name %>
      <%= t.genre %>
      <%= t.address %>
      <%= t.cost %>
      <%= t.about %>
      <%= t.date %>
      
      <div>
      <h2>総合評価：
      <span class="star-rating">
         <span class="star-rating-front" style="width: <%= getPercent(t.overall) %>%;">★★★★★</span>
         <span class="star-rating-back">★★★★★</span>
      </span> 
      </h2>
      </div>

      <% if user_signed_in? %>
      <% if current_user.already_liked?(t) %>
          <%= button_to food_like_path(id: t.id, food_id: t.id), method: :delete do %>
              <p>いいねを取り消す</p><%= t.likes.count %>
          <% end %>
      <% else %>
          <%= button_to food_likes_path(id: t.id, food_id: t.id), method: :food do %>
              <p>いいね</p><%= t.likes.count %>
          <% end %>
      <% end %>
  <% else %>
      <p>いいねの数 = </p><%= t.likes.count %>
  <% end %>

      <%= link_to "詳細へ", food_path(t.id) %>  
      <%= link_to "編集する", edit_food_path(t.id) %>
      <%= button_to "削除する", food_path(t.id), method: :delete %>
    </div>
  <% end %>
</div>

<h2>gmap</h2>

<div id='map'></div>

<style>
#map {
  height: 600px;
  width: 600px;
}
</style>

<!-- js部分 -->
<script>
    function initMap() {

      //初期表示位置
      let latlng = new google.maps.LatLng(38.60, 139.5);
      //デザイン
      let styles = [
           {
            stylers: [
             { "saturation": 0 },
             { "lightness": 0 }
            ]
           }
          ];

      let map = new google.maps.Map(document.getElementById('map'), {
          zoom: 5.5,
          styles: styles,
          center: latlng
      });
      let transitLayer = new google.maps.TransitLayer();
      transitLayer.setMap(map);

//複数マーカー ここから
      <% @foods.each do |food|%>
        ( function() { 
          let markerLatLng = { lat: <%= food.lat %>, lng: <%= food.lng %> }; // 緯度経度のデータ作成
          let marker = new google.maps.Marker({ 
            position: markerLatLng, 
            map: map 
          });
//マーカーをクリックしたとき、詳細情報を表示
          let infowindow = new google.maps.InfoWindow({
            position: markerLatLng,
            content: "<a href='<%= food_url(food.id) %>' target='_blank'><%= food.name %></a>"
          }); //ここで詳細ページへのリンクを表示させる
          marker.addListener('click', function() {
            infowindow.open(map, marker);
          });

       })();
      <% end %>
      //複数マーカー ここまで  
    } 
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAA4mNa8QKOk9FbkMkcshWkwi6xcOL047k&callback=initMap" async defer></script>
<%= paginate @foods %>

app/views/foods/new.html.erb
<h1>中目黒グルメサイト</h1>
<h3>新規投稿ページ</h3>
<%= form_with(model: @foods, local: true) do |f| %>

  <div class="field">
    <%= f.label :店の名前 %>
    <%= f.text_field :name, :size => 30 %>
  </div>


  <div class="field">
    <%= f.label :ジャンル  %>
    <%= f.select :genre, 
    [["イタリアン", "イタリアン"], 
    ["中華", "中華"], 
    ["和食", "和食"]], include_blank: "選択して下さい" %>
  </div>

  <div class="field">
  <%= f.label :所要時間  %>
  <%= f.select :address, 
  [["5分以内", "5分以内"], 
  ["5~10分", "5~10分"], 
  ["15分以上", "15分以上"]], include_blank: "選択して下さい" %>
  </div>

  <div class="field">
    <%= f.label :相場  %>
    <%= f.number_field :cost, :size => 10 %>
  </div>

  <div class="field">
    <%= f.label :感想  %>
    <%= f.text_area :about, :size => "30x2" %>
  </div>

  <div class="field">
  <%= f.label :image %>
  <%= f.file_field :image %>
</div>

<h5>総合評価</h5>
   <div class="food_form">
    <%= f.radio_button :overall, 5 ,id: 'star1'%>
    <label for="star1"><span class="text">最高</span>★</label>

    <%= f.radio_button :overall, 4 ,id: 'star2'%>
    <label for="star2"><span class="text">良い</span>★</label>

    <%= f.radio_button :overall, 3 ,id: 'star3'%>
    <label for="star3"><span class="text">普通</span>★</label>

    <%= f.radio_button :overall, 2 ,id: 'star4'%>
    <label for="star4"><span class="text">悪い</span>★</label>

    <%= f.radio_button :overall, 1 ,id: 'star5'%>
    <label for="star5"><span class="text">最悪</span>★</label>
 </div>

 
  <div class="actions">
    <%= f.label :lat,"緯度" %>
    <%= f.text_field :lat,:value =>"緯度", id: :lat %>
    <%= f.label :lng,"経度" %>
    <%= f.text_field :lng,:value =>"経度", id: :lng %>
  </div>
  
  <%= f.submit "投稿する" %>
  <% end %>
 

<h2>Map</h2>

<input id="address" type="textbox" value="GeekSalon">
<input type="button" value="検索" onclick="codeAddress()">
<p>マーカーをドラック＆ドロップで位置の調整ができます。<p>

<div id='map'></div>

<style>
#map {
  height: 600px;
  width: 600px;
}
</style>

<script>
//初期マップの設定
let map
let marker
function initMap(){
  geocoder = new google.maps.Geocoder()

  map = new google.maps.Map(document.getElementById('map'), {
    center:  {lat: 35.6803997, lng:139.7690174},  //東京
    zoom: 15,
    
  });
}

//検索後のマップ作成
let geocoder
let aft
function codeAddress(){
  let inputAddress = document.getElementById('address').value;
  geocoder.geocode( { 'address': inputAddress}, function(results, status) {
    if (status == 'OK') {
        //マーカーが複数できないようにする
        if (aft == true){
            marker.setMap(null);
        }

        //新しくマーカーを作成する
        map.setCenter(results[0].geometry.location);
            marker = new google.maps.Marker({
            map: map,
            position: results[0].geometry.location,
            draggable: true	// ドラッグ可能にする
        });

        //二度目以降か判断
        aft = true

        //検索した時に緯度経度を入力する
        document.getElementById('lat').value = results[0].geometry.location.lat();
        document.getElementById('lng').value = results[0].geometry.location.lng();

        // マーカーのドロップ（ドラッグ終了）時のイベント
        google.maps.event.addListener( marker, 'dragend', function(ev){
            // イベントの引数evの、プロパティ.latLngが緯度経度
            document.getElementById('lat').value = ev.latLng.lat();
            document.getElementById('lng').value = ev.latLng.lng();
        });
    } else {
      alert('該当する結果がありませんでした：' + status);
    }
  });   
}

</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAA4mNa8QKOk9FbkMkcshWkwi6xcOL047k&callback=initMap" async defer></script>



<%= link_to "一覧に戻る", foods_path %>

app/views/foods/show.html.erb
<h1>Nakamemeshi</h1>
<h3>グルメ詳細</h3>
<div class="food">
  <p><%= @food.name %></p>
  <p><%= @food.genre %></p>
  <p><%= @food.address %></p>
  <p><%= @food.cost %></p>
  <p><%= @food.about %></p>

  <div>
<h2>総合評価：
<span class="star-rating">
   <span class="star-rating-front" style="width: <%= getPercent(@food.overall) %>%;">★★★★★</span>
   <span class="star-rating-back">★★★★★</span>
</span> 
</h2>
</div>
<%= image_tag @food.image_url, size: "250x200" if @food.image? %>
  <p><%= @food.created_at %></p>
</div>



<% if user_signed_in? %>
      <% if current_user.already_liked?(@food) %>
        <%= button_to food_like_path(@food), method: :delete do %>
          <p>いいねを取り消す</p><%= @food.likes.count %>
        <% end %>
      <% else %>
        <%= button_to food_likes_path(@food), method: :food do %>
          <p>いいね</p><%= @food.likes.count %>
        <% end %>
      <% end %>
    <% else %>
      <p>いいねの数 = </p><%= @food.likes.count %>
    <% end %>
  <%= link_to "編集する", edit_food_path(@food.id) %>
</div>

<h2>いいねしたユーザー</h2>
<% @food.liked_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>
<div class="comment-wrapper">
  <p>コメント一覧</p>
  <% @comments.each do |c| %>
    <div>
      <%= c.user.email unless c.user.blank? %>
      <br>
      <%= c.content %>
    </div>
      <br>
  <% end %>

  <% if user_signed_in? %>
    <%= form_with(model: [@food, @comment], local: true) do |f| %>
      <%= f.text_area :content %>
      <%= button_tag type: "submit" do %>
        <i class="far fa-comments"></i> コメントする
      <% end %>
    <% end %>
  <% end %>
</div>
<%= link_to "グルメ一覧に戻る", foods_path %>